<a href="https://colab.research.google.com/github/kejsida33/kejsis/blob/master/laborator1_kejsi_koci.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducere
- Google Colabs
- GitHub
- Python


#Python
**Librării utile**
- Numpy
- Panda
- scikit-learn
- Matplotlib
- Keras



In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import scipy.io as sio
import keras


#Noțiuni de bază

**Operații simple**

In [ ]:
a = 5
b = 7
s1 = a+b
s2 = a-b
s3 = a/b
s4 = a*b
print('Rezultatul adunării este:'+ str(s1)) #funția str() - transformă numărul in stringș funcția print() afișează variabila
print('Rezultatul scăderii este:'+ str(s2))
print('Rezultatul impărțirii este:'+ str(s3))
print('Rezultatul înmulțirii este:'+ str(s4))
print(type(a))

Rezultatul adunării este:12
Rezultatul scăderii este:-2
Rezultatul impărțirii este:0.7142857142857143
Rezultatul înmulțirii este:35
<class 'int'>


**Vectori si matrici**

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10]
print(a)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = list(range(1,10)) #try changing range(1,11)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
a = np.random.randn(10)
print('10 numere aleatorii')
print(a)
a = 10+np.random.randn(10)
print(a)

10 numere aleatorii
[-1.46252682 -0.45438153  0.65319783 -0.26437061 -0.10436377  0.39156967
  1.03895702  1.34623672 -0.14455856  0.05242762]
[10.32952841 11.3708116  10.00944289  8.0142988   9.89237174  9.06327786
 11.4601445  10.54039175  9.51902055  9.79107622]


In [ ]:
a = [[0, 0, 0, 0],
     [0, 0, 0, 0],
     [0, 0, 0, 0],
     [0, 0, 0, 0]]
print(a)
print(type(a))

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
<class 'list'>


In [ ]:
a = np.zeros((4,4))
print(a)
print(type(a))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [ ]:
a = [[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

print('Primul rand din matrice')
print(a[0])
print('Primul element din matrice')
print(a[0][0])
print('Elementul i=2 (rand), j=1(coloana)')
print(a[2][1])
print(type(a))

Primul rand din matrice
[1, 4, 5, 12]
Primul element din matrice
1
Elementul i=2 (rand), j=1(coloana)
7
<class 'list'>


#Exercițiu 1a
Calculați și afișați valoarea:
[3546 + (7901-621)] * 2




In [ ]:
print("Valoarea expresiei este: ", (3546 + (7901 -621))*2)

Valoarea expresiei este:  21652


#Exercițiu 1b
1.Creați și afișați o matrice de (3,3) elemente

2.Afișați elementul de pe linia trei coloana trei a matricei create

In [ ]:
a = np.array([[1, 3, 5],
                    [7, 8, 12],
                    [12, 35, 70]])
print(a)
print(a[2][2])

[[ 1  3  5]
 [ 7  8 12]
 [12 35 70]]
70


#Exercițiu 1c
1. Folosind librăria numpy, creați și afișați o matrice de (5,5) cu elemente aleatorii de la 1 la 100.
Utilizați funcția numpy - np.random.randint(nr max, size=(x,x))

2. Afișați elementul de la intersecția celor două diagonale ale matricei

3. Aranjați crescător elementele de pe a doua coloană a matricei și afișați rezultatul. *funcția numpy sort()*

4. Folosiți funcția *size()* și afișați rezultatul

5. Afișați lungimea matricei. *funcția len()*


In [ ]:
a = np.random.randint(1, 100, size=(5,5))
print(a)
print("Elementul de la intersectia celor doua diagonale este:", matrice[2][2])
second_column = a[:, 1]
print(np.sort(second_column))
print("Dimensiunea este:", np.size(a))
print("Lungimea este:", len(a))

[[78 98 78 72 68]
 [54 68 55 35 29]
 [ 3 60 39  3 12]
 [21 17 63 18 18]
 [75 27 86 16 94]]
Elementul de la intersectia celor doua diagonale este: 75
[17 27 60 68 98]
Dimensiunea este: 25
Lungimea este: 5


#Operații condiționale și repetitive

**Operatii conditionale**

Sintaxa

```
if <expression>:
  <statement>

```
```
if <expression>:
  <statement>
else:
  <statement>
```

```
if <expression>:
  <statement>
elif <expression>:
  <statement>
else <expression>:
  statement>
```
Exemple





    
  




**Operatori logici**


*   x < y  
*   x > y
*   x <= y
*   x >- y
*   x == y
*   x != y
*   x or y
*   x and y



**Operatii repetitive**

Sintaxa

```
for <variabila> in <vector>:
  <statement>
```


```
while <expresie>:
  <statement>
```

Exemple





# Exercitiu 2a
Creati un element aleatoriu intre 1 si 10. Utilizați funcția numpy - np.random.randint(nr max, size=(x,x)). In functie de valoarea elementului, afisati:


*   *Numarul generat este mai mic decat 5*
*   *Numarul generat este intre 5 si 8*
*   *Numarul generat este mai mare decat 8*

Afisati numarul generat.




In [ ]:
numar_aleator = np.random.randint(1, 11)
print(numar_aleator)
if numar_aleator > 5:
  print("Numarul generat este mai mare decat 8!")
elif numar_aleator <=8 and numar_aleator >=5:
  print("Numarul generat este intre 5 si 8!")
else:
  print("Numarul generat este mai mic decat 5!")


5
Numarul generat este intre 5 si 8!


# Exercitiu 2b
Calculati factorial de 10 (10! = 1* 2 * 3 * 4 *....) folosing o functie repetitiva.





In [ ]:
def fact(n):
  if n == 0:
    return 1
  else:
    return n*fact(n-1)

print(fact(10))

3628800
